name: Deploy ETL to AWS Lambda

# Starter
on:
  push:
    branches:
      - main  # Roda sempre que houver push na branch main
    paths:
      - '**.py'          # Roda se mudar arquivos Python
      - 'Dockerfile'     # Roda se mudar o Dockerfile
      - 'requirements.txt' # Roda se mudar as dependências

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest # Ambiente de Execução

    steps:
    # Baixar o código do seu repositório
    - name: Checkout code
      uses: actions/checkout@v4

    # Logar na AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    # Logar no ECR 
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Construir, Taggear e Enviar a Imagem Docker
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: projeto-futebol 
        IMAGE_TAG: latest
      run: |
        # 1. Build da imagem
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        
        # 2. Push para a AWS
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # Atualizar o Lambda (enviar e recarregar)
    - name: Update Lambda Function
      env:
        LAMBDA_NAME: football_projeto_daily
      run: |
        aws lambda update-function-code \
          --function-name $LAMBDA_NAME \
          --image-uri ${{ steps.login-ecr.outputs.registry }}/projeto-futebol:latest \
          --publish