name: Deploy ETL to AWS Lambda

# Starter
on:
  push:
    branches:
      - main       # Roda na branch main apenas se:
    paths:
      - '**.py'          # mudar arquivos Python
      - 'Dockerfile'     # mudar o Dockerfile
      - 'requirements.txt' # mudar as dependências

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest # Ambiente de Execução

    steps:
    # Baixar o código do seu repositório
    - name: Checkout code
      uses: actions/checkout@v4

    # Logar na AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    # Logar no ECR 
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Construir, Taggear e Enviar a Imagem Docker
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: projeto-futebol 
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # Atualizar o Lambda (enviar e recarregar)
    - name: Update Lambda Function
      env:
        LAMBDA_NAME: football_projeto_daily
      run: |
        aws lambda update-function-code \
          --function-name $LAMBDA_NAME \
          --image-uri ${{ steps.login-ecr.outputs.registry }}/projeto-futebol:latest \
          --publish

    # Enviar o Script do Glue para o S3
    - name: Upload Glue Script to S3
      env:
        BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }} 
      run: |
        aws s3 cp etl_script.py s3://$BUCKET_NAME/scripts/etl_script.py
        
        echo "Script Glue atualizado com sucesso no S3!"